# SEO Values
title: Luke Blog
tagline: productivity
description: productivity
url: https://devj-luke.github.io/
twitter: https://twitter.com/devj_luke
logo: https://twitter.com/devj_luke/photo

# Google Analytics ID
google_analytics:

# GitHub Values
github:
  owner_name: luke
  owner_url: https://github.com/devj-luke
  repository_url: https://github.com/devj-luke

show_downloads: true
show_header: true
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
